version: "3.9"

services:
  product-api:
    build: .
    container_name: product-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app/data/products.json:/app/data/products.json
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
